version: '3.7'
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=sakila
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - provisioning-mysql:/data/db
volumes:
  provisioning-mysql: {}