version: '3.7'
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      provisioning-mysql: /data/db
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS ${MYSQL_APP_DB}; CREATE DATABASE IF NOT EXISTS ${MYSQL_KEYCLOAK_DB};' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
  postgres:
      image: postgres:10.5
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5438:5432'
volumes:
  provisioning-mysql: {}
