server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://root:root@localhost:3306/sakila
  jpa:
    generate-ddl: true
    debug: true
  sql:
   init:
     mode: always
  thymeleaf:
    reactive:
      max-chunk-size=8192: logging

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
logging:
  level:
    org:
      springframework:
        security: DEBUG