spring:
  r2dbc:
    url: r2dbc:mysql://root:root@localhost:3306/sakila
  jpa:
    generate-ddl: true
    debug: true
  sql:
   init:
     mode: always
  thymeleaf:
    reactive:
      max-chunk-size=8192: logging
  level:
      org:
        springframework:
          r2dbc: DEBUG
  mail:
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
